title = "🌿 Ragy Notes 📚"
baseURL = "https://ragynotes.github.io"
languageCode = "en-us"
theme = "zen"
# themesDir = "../.."
# resourceDir = "../resources"

publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
# googleAnalytics = ""
enableRobotsTXT = true

# [languages]
#   [languages.en]
#     title = "My blog"
#     weight = 1
#     contentDir = "content/en"
#   [languages.fr]
#     title = "Mon blogue"
#     weight = 2
#     contentDir = "content/fr"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[author]
  author = "Pesky"
url = "https://github.com/pskyhx"
avatar = "https://avatars.githubusercontent.com/u/88959296"

[params]
  author = "Pesky"
  favicon = ""
  site_logo = ""
  description = "notes on the context of kratom"
  github = "ragynotes"

  contact = "info@example.org"
  copyright = "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  dateformat = "January 2, 2006"
  favicon = "apple-touch-icon.png"
  feedlinks = true
  footer = "Generated by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen). website source at [github 🍃 repo](https://github.com/ragynotes/ragynotes.github.io)"
  icon = "apple-touch-icon.png"
  image = "apple-touch-icon.png"
  imageMaxWidth = 400
  mobileMenu = true
  poweredby = false
  sidebar = true
  submitted = true
  # gitlab = ""
 #  linkedin = ""
 #  mastodon = ""
 #  slack = ""
 #  stackoverflow = ""
 #  rss = ""
  # facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  # instagram = ""
  # youtube = ""


[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchIndex" ]
section = [ "HTML", "RSS", "JSON" ]

[taxonomies]
	category = "categories"
	tag = "tags"

	originalyear = "Publication year"
	originalformat = "Publication format"
		#examples:
		# "Scientific journal"
		# "Government document",
		# "Popular periodical",
		# "Advertisement",
		# "Legislation and legal proceeding"
		# "Book"
		# "None"
	originaltopic = "Publication topic"	
		#examples:
		# "Ethnobotany",
		# "Taxonomy and botany",
		# "Legislation",
		# "Social issues",
		# "Stigmatized drug use and addiction",
		# "Money and wealth"
		# "Religion",
		# "Morality"
		# "None"

enableEmoji =  "true"
enableGitInfo =  "enableGitInfo "

[markup]
	defaultMarkdownHandler = "goldmark"
	
	[markup.asciidocExt]
		backend = "html5"
		extensions = []
		failureLevel = "fatal"
		noHeaderOrFooter = true
		preserveTOC = false
		sectionNumbers = true
		trace = false
		verbose = false
		workingFolderCurrent = false

[markup.goldmark]
	[markup.goldmark.extensions]
		definitionList = true
		footnote = true
		linkify = true
		strikethrough = true
		table = true
		taskList = true
		typographer = true

	[markup.goldmark.parser]
		autoHeadingID = true
		autoHeadingIDType = "github"
		[markup.goldmark.parser.attribute]
			block = false
			title = true

	[markup.goldmark.renderer]
		hardWraps = false
		unsafe = false
		xhtml = false

	[markup.highlight]
		codeFences = true
		guessSyntax = true

	[markup.tableOfContents]
		endLevel = 3
		ordered = true
		startLevel = 2









